### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by julianwachholz** [Doridian/CorsairLinkPlusPlus#1]
Hey there!

I would love to see installation instructions for this project, as I'm a complete beginner and after trying to get it to run for about an hour with NuGet etc. I gave up. Probably missed something somewhere.

I'd love to test this and give you feedback!

**Comment by SimonSchick** [comment]
All the packages should be automatically installed upon building the solution.

What version of VS are you using?

**Comment by julianwachholz** [comment]
There's no Visual Studio on Linux. I thought this was for Linux?

**Comment by Doridian** [comment]
For NuGet I use (remember to import the root certificates into mono: mozroots --import --sync):

```
mono /path/to/nuget.exe restore
xbuild /p:Configuration="Release NoWeb"
```

For building the web view:

```
cd CorsairLinkPlusPlus.WebView
npm install
bower install
grunt --force
cd ..
cp -rp CorsairLinkPlusPlus.WebView/bin/Release dist/CorsairLinkPlusPlus.RESTAPI/web
```

**Comment by julianwachholz** [comment]
Okay cool thanks @Doridian - I think I got this far, but xbuild doesn't create a `dist` folder but creates releases in every subfolder.

How do I run it after that? Which thing should be started first etc.?

**Comment by Doridian** [comment]
Well, just copy the stuff to a dist folder then.
And, well, there is only one thing you start.
Either the WebUI (RESTAPI) project after copy cpied the web files over (changing paths from my instructions above)
Or you run the CLI system which just prints you info repeatedly so you can check the status in a terminal.
You can even run both at once, if you want to, but there is no reason to do so.

**Comment by julianwachholz** [comment]
Alright thank you, I figured out that `CorsairLinkPlusPlus.RESTAPI.exe` runs a webserver on port 38012 - which it should output to make it easy to find.

This is what I get:

![](http://i.imgur.com/9uzlFEh.png)

**Comment by SimonSchick** [comment]
I am currently in the process of refactoring a few things in the web view.

Also please post your LINK device configuration(what devices, connections etc).

**Comment by julianwachholz** [comment]
Heya, I just recently installed the Corsair H100i and connected the USB cable to the first internal USB header on my ASUS Z97-A motherboard.

**Comment by SimonSchick** [comment]
Did you close CorsairLINK before launching the API server/webview?

Corsair LINK and our driver cannot run at the same time due to the lack of locks in the corsair software.

**Comment by SimonSchick** [comment]
Nevermind you are running Linux.

Have you tried running it as root?

**Comment by julianwachholz** [comment]
Yep, it's the same when I try to run as root.

**Comment by louis54000** [comment]
Hi ! I built the project on Visual Studio 2013 (Win 8.1), it runs fine, execpt webserver. I can send requests manually and I get json response, but when trying to access http://localhost:38012/ {"success":false,"result":"Static content not found"} /api and all requests work tho. Any suggestions? Awesome work by the way! 
Edit : I fixed it somehow... Program.WEB_ROOT_ABSOLUTE + '/' + absoluteUri was not pointing to the web files. Changed it to my folder and got rid of       if (directory == null) { /***/ } 
Detects my ax860i, all values here! Awesome man!
I'm going to make a little widget with your api ! Awesome!

**Comment by louis54000** [comment]
I wrote my widget it works fine thanks to your api. It just stops working after a while. I don't know why. After a certain number of requests it stops and eventually crashes. "A first chance exception of type 'Griffin.Net.Buffers.PoolEmptyException' occurred in Griffin.Core.dll"

**Comment by AgentB1** [comment]
Hi @Doridian 

 I'm close to getting this running on Ubuntu Linix 1404.  After the xbuild 

home/agentb/CorsairLinkPlusPlus/CorsairLinkPlusPlus.sln (default targets) ->
(Build target) ->
/home/agentb/CorsairLinkPlusPlus/CorsairLinkPlusPlus.Driver.CorsairLink/CorsairLinkPlusPlus.Driver.CorsairLink.csproj (default targets) ->
/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

```
USB/BaseUSBDevice.cs(23,7): error CS0246: The type or namespace name `HidSharp' could not be found. Are you missing an assembly reference?
```

# <snip repeated hidsharp errors>

This led to trying to find how to get hidsharp to xbuild.  which is where i'm stuck.  

I have downloaded from here http://www.zer7.com/software/hidsharp- is that the correct hidsharp ?  
If so it's not easy to work out why it is not xbuilding either.

Appreciate any pointers...

**Comment by Doridian** [comment]
Usually NuGet can get you a build of that by itself.
I thought it had Linux builds in repo...

**Comment by Doridian** [comment]
Usually NuGet can get you a build of that by itself.
I thought it had Linux builds in repo...

**Comment by julianwachholz** [comment]
There are no builds in the repository, but it would be very appreciated if you'd put them under Releases. :)

**Comment by stvnmbr1** [comment]
still can't get this to work .. i tried opencorsairlink too but that isn't working yet.. I have xpenology with debian chroot. I'm trying to get the output from the link to nagios. but first i got to get he link working :)

right now a can't even get past the build.. I'm still a noob in debian/linux but i'm a quick learner ;)

i get errors on assembly thet it can't find hid sharp and hid device. asking for a powershell dll

tried anything you posted, i really don't get the nuget and can't get this to work here, but a little help would be needed :) it's probably a fast fix, i hope ;)

**Comment by stvnmbr1** [comment]
and just need the CLI :) 

nuget gives some error that it can't restore by default

tried also
mono ./nuget.exe restore

xbuild /p:Configuration="Release NoWeb" CorsairLinkPlusPlus.sln

**Comment by mlaznar** [comment]
Hello there,

I am very interested in running this app...

I am using Windows, I could not find any installations instructions, so please can you describe the instruccions step by step to make this working so far

I opened VS and generate the 5 projects that are present in the solution, but from there I am a litle losted...

Thanks for all in advance
Manuel
