### ISSUE TITLE
Corsair Link for power supplies

### ISSUE THREAD

**Issue by nogweii** [Doridian/CorsairLinkPlusPlus#2]
Doesn't seem like CL++ supports power supplies yet.

Running on Windows 8.1 and I get this:

![corsairlink_plusplus_no_view](https://cloud.githubusercontent.com/assets/14547/5061130/08ccdd54-6d41-11e4-8b5c-76f633e5526f.png)

Along with the error message `Error: File Gui/Views/Devices/RootDevice has not been loaded` twice.

**Comment by Doridian** [comment]
It supports PSUs.
However: It does not support the dongle included with the PSUs since that uses an entirely different protocol (USBXPress) rather than standard HID.
Also, it does not support running while CorsairLink is running (it would run but since it cannot interlock with CL it would cause almost all the devices to crash in a few minutes)

**Comment by GrandAdmiralThrawn** [comment]
Would you care for supporting the USBXPress interface in the future? It's using a Silicon Labs bridge chip, that appears to have a rather complete API documentation (plus a driver for Windows). See here for the documentation:

http://www.silabs.com/Support%20Documents/TechnicalDocs/an169.pdf

If you could use the API, all the user would need is the Silabs driver (which is included in Corsair Link) to talk to a Corsair AX1200i via the USB dongle for instance.

There is more to it even: If we compile/link your code with a proper platform target, this can work on older Windows systems too, that Corsair Link doesn't run on (but that the Silabs driver does!), like XP, XP x64, Server 2003 etc.

Worth it? I can't do it myself unfortunately, so I have to ask you for it...

**Comment by AgentB1** [comment]
@Doridian hi - firstly thanks for doing this github - Corsair could have offered some help at least in documenting some of the protocol, i think its quite amazing what has been achieved with so little.

I have a hx750i and will be trying to get CL++ running.

Thanks again.

**Comment by MarcSN311** [comment]
@AgentB1 Have you been able to get hx750i working?

**Comment by AgentB1** [comment]
No I lost interest, i ran virtualBox and set up a VM to monitor the few times i needed it.  I won't buy Corsair products for Linux equipment in the future, and as I've left Windows that means goodbye to Corsair for anything that needs its  software to work.  Shame really the hardware is high quality but the  software (even Windows) poor.

**Comment by audiohacked** [comment]
@AgentB1 I'm assuming most people don't have the HX750i, us developers are unable to add support without supporting information. Needed info is the Product ID and a dump of the USB descriptors for the HX750i. Stuff found in 'lsusb'.

**Comment by AgentB1** [comment]
@audiohacked, yes until Corsair release that information, i'm inclined to agree with zanny's comments on [Phoronix](http://www.phoronix.com/scan.php?page=news_item&px=MTgyMDc)

**Comment by Doridian** [comment]
Just to weigh in myself a bit: The main issue I had with the USBxpress: I could find the DLL with unclear licensing, sure. But as I wrote this tool to be cross-platform (and used it on non-Windows OS myself), it would be kind of hard for me to develop and/or maintain with this "random" binary blob.

However, right now any kind of development from me is limited anyway (which hasn't been needed in a while as the functionality stayed working pretty well), since Windows 10 Creators Update made the drivers no longer work for me (so I cannot even test booting into Windows to support new devices)

**Comment by audiohacked** [comment]
@AgentB1 I don't think you heard what I said. You can give enough information for me to implement support for your HX750i under Linux. I already reverse engineered most of the CorsairLink protocols, including the USBxpress. I'll also add most of the commenters on Phoronix are just "users" who have no idea how to fix their own system if systemd fucks up!

**Comment by mvastola** [comment]
@audiohacked, I just got an HX850i. I'd love to help you get this up and working. Here is my dump from `lsusb`. Is there anything else you might need? Would happy to supply it to you and test/help debug.

Just me know! Thanks so much!

````
mvastola@vastdesk:~$ sudo lsusb -d 1b1c: -vvvv
[sudo] password for mvastola:

Bus 005 Device 002: ID 1b1c:1c06 Corsair
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x1b1c Corsair
  idProduct          0x1c06
  bcdDevice            0.02
  iManufacturer           1                      
  iProduct                2                      
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      28
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0001
  Self Powered
````
