### ISSUE TITLE
Corsair CLI crash

### ISSUE THREAD

**Issue by FallenHorseman** [Doridian/CorsairLinkPlusPlus#3]
I'm triing to get the CLi running. 
When I execute the exe I throw with an exception after reading the temperature:

![issue](https://cloud.githubusercontent.com/assets/7870679/8339379/4536a74c-1ab7-11e5-9719-554145695cc6.JPG)

'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll
Additional info: 
Key isn't registered in the Library

Below some hopefully informations:

Microsoft Visual Studio Community 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51209
![issue2](https://cloud.githubusercontent.com/assets/7870679/8339405/7669da78-1ab7-11e5-94a9-a7038d1fc88f.JPG)

Did you have any Ideas?

**Comment by Doridian** [comment]
It is weird that it seems to try to access sensor idx 3 when there is only 1.
A stacktrace would be very helpful so I can see what triggered this codepath
